<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Sign in</name>
   <tag></tag>
   <elementGuidId>e4aab3e2-b0af-46fe-94ba-0d7552ef319a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_ucHeader_pnlSignin']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.sign-in</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fd7453f1-cd96-401c-b79a-aae0e1acc5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/account/account.aspx?lang=vn</value>
      <webElementGuid>aa71455d-f9c1-482e-b256-24bec48ba9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>dca8fef3-c30b-406d-9c37-0225f3274bff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sign-in</value>
      <webElementGuid>72e0988d-f0c6-470d-9750-98939e38b4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign in</value>
      <webElementGuid>a59e76af-630a-4f0d-8b64-edec10094d28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_ucHeader_pnlSignin&quot;)/a[@class=&quot;sign-in&quot;]</value>
      <webElementGuid>81344096-f324-4c8e-9b4c-fc204f213892</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_ucHeader_pnlSignin']/a</value>
      <webElementGuid>9bda7611-128d-4159-b2da-09ca8e87e161</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Sign in')]</value>
      <webElementGuid>229f56a5-3289-4816-8195-a986511ef981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/account/account.aspx?lang=vn')])[2]</value>
      <webElementGuid>b86c61ae-e773-47b8-9c4b-d618a6222d1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/a</value>
      <webElementGuid>78463229-3066-4cf0-ab7f-aa3cbe334693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/account/account.aspx?lang=vn' and @title = 'Sign in' and (text() = 'Sign in' or . = 'Sign in')]</value>
      <webElementGuid>00dfe326-9f6e-4083-bde7-83dea19651bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
