<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucLogintxtPassword</name>
   <tag></tag>
   <elementGuidId>f87fac70-700f-43a1-af97-e471977fb299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucLogin_txtPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucLogin_txtPassword</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fbf0bd2-bb17-4317-9333-d3588a5abb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucLogin$txtPassword</value>
      <webElementGuid>6a46dda2-f5f7-4f2a-93ab-60ebdd77851e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7968af9e-0f3b-410e-8a7c-edaed553441c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>b1edc4ec-b6ea-486f-84ef-b9dbbf9e1b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucLogin_txtPassword</value>
      <webElementGuid>ecfd5e4e-e098-4dc8-af37-d58c034465e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucLogin_txtPassword&quot;)</value>
      <webElementGuid>1cfbfdd6-c01e-4285-b66e-3f6c323558a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucLogin_txtPassword']</value>
      <webElementGuid>4242cc07-8131-4cb5-8b45-cc6c3a8bb1e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucLogin_pnlLogin']/div[3]/input</value>
      <webElementGuid>132fb3e1-4a3d-4aab-845f-b2aeeeb58f22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/input</value>
      <webElementGuid>a591342a-5a50-4fe6-8854-c5fe14cfadeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphContent$ucLogin$txtPassword' and @type = 'password' and @id = 'ctl00_cphContent_ucLogin_txtPassword']</value>
      <webElementGuid>ec6a819f-7795-4004-bb27-d54cbc1c7fe3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
