<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucRegisterbtnRegister</name>
   <tag></tag>
   <elementGuidId>9081b57b-bb2b-4304-9549-570da8b18b84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucRegister_btnRegister']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucRegister_btnRegister</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e033473-e26f-4d1f-98d4-7a9ffafe25a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>9bad0de0-3276-4a60-86c3-6d41d5367e79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucRegister$btnRegister</value>
      <webElementGuid>daadd4cc-5886-4d19-bf1c-9b619cd35767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Tạo tài khoản mới</value>
      <webElementGuid>3b389581-e310-4050-a3bf-7df9bcd39bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucRegister_btnRegister</value>
      <webElementGuid>ce8abf48-9e4b-4782-b9a2-a5436c7f148e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>create</value>
      <webElementGuid>8dc06e36-103f-4e6b-a331-3ceb8c1e88a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucRegister_btnRegister&quot;)</value>
      <webElementGuid>ed4a3de4-4d8b-496d-b6a4-62b11fb88c3f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucRegister_btnRegister']</value>
      <webElementGuid>42aa74d0-f553-4749-b1df-99de83e550e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucRegister_pnlLogin']/div[7]/input</value>
      <webElementGuid>3d64297c-6509-42e2-8c4f-b806a09bd99f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/input</value>
      <webElementGuid>6ac52f80-b73c-481d-be4e-633d95cb7e6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$cphContent$ucRegister$btnRegister' and @id = 'ctl00_cphContent_ucRegister_btnRegister']</value>
      <webElementGuid>1f98570e-5f53-4828-8f93-0ceb26d39c0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
