<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucLoginbtnLogin</name>
   <tag></tag>
   <elementGuidId>60aa3cfc-752f-4783-a722-495e507b3323</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucLogin_btnLogin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucLogin_btnLogin</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>172b0f5c-7bd9-47e4-bb0f-f139ab2f0465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f139fef6-0508-4333-aeaa-a9a04e310fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucLogin$btnLogin</value>
      <webElementGuid>ca84080a-3321-4156-8bc7-55570642a07e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ĐĂNG NHẬP</value>
      <webElementGuid>2698333a-2b8f-49d0-a712-65e4a5a7f8a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucLogin_btnLogin</value>
      <webElementGuid>5c44199d-90d2-4e88-b598-a2a3653a5581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>121b079c-24df-4b89-b0ce-b5c8af88cf66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucLogin_btnLogin&quot;)</value>
      <webElementGuid>3721ccdf-11f1-4f82-a63e-5a5ca95e9287</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucLogin_btnLogin']</value>
      <webElementGuid>8a5158f0-01fc-4f85-a778-1c4a4a212e68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucLogin_pnlLogin']/div[5]/input</value>
      <webElementGuid>cd81dc45-51c8-43fe-82a2-2486a2205872</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[5]/input</value>
      <webElementGuid>870d3c17-c26a-415f-8a95-5957be071c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'ctl00$cphContent$ucLogin$btnLogin' and @id = 'ctl00_cphContent_ucLogin_btnLogin']</value>
      <webElementGuid>c6d1b592-5467-45ea-ae5a-6f67bf3e4341</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
