<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ctl00cphContentucLogintxtEmail</name>
   <tag></tag>
   <elementGuidId>99748c08-f26f-44f5-82cf-f8aeccb48052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_cphContent_ucLogin_txtEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_cphContent_ucLogin_txtEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac2bb9c8-049f-4728-ba1d-dc0c7b056701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$cphContent$ucLogin$txtEmail</value>
      <webElementGuid>f34a3b0a-3701-43f0-b742-c111b03d7e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6c9d9ecd-19b3-4af9-8b4e-3ffa88947627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>8897b6fe-ac3d-4978-89a7-69f0a870b22b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_cphContent_ucLogin_txtEmail</value>
      <webElementGuid>91e6050a-1d2c-4054-80ba-76c46d591504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_cphContent_ucLogin_txtEmail&quot;)</value>
      <webElementGuid>c7b3a311-ac64-40c0-b878-bf3969e5f5c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_cphContent_ucLogin_txtEmail']</value>
      <webElementGuid>84fe6015-f47b-4176-834a-921d242d5471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_cphContent_ucLogin_pnlLogin']/div[2]/input</value>
      <webElementGuid>7851b140-fe39-4a56-a81c-b5159f2e130c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>7d8d6666-bee9-4440-8f8b-6f03f916d3ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'ctl00$cphContent$ucLogin$txtEmail' and @type = 'text' and @id = 'ctl00_cphContent_ucLogin_txtEmail']</value>
      <webElementGuid>cf4dbcbb-5be2-4920-8f77-edbf9f666bc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
